version: 2.1
orbs:
  slack: circleci/slack@3.3.0
jobs:
  build:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - run: make test
      # TODO(milas): fix lint issues + enable
      # - run: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.30.0 && make golangci-lint
      - store_test_results:
          path: test-results
      - slack/notify-on-failure:
          only_for_branches: main

workflows:
  version: 2
  build:
    jobs:
      - build
